### PR TITLE
feat: set default save path to cwd

### PR DESCRIPTION
**Pull request by Bekaboo**
This PR sets the default save path to cwd. I find it more convenient in most cases.

### CODE REVIEW

**Comment by benlubas** [comment]
So the default behavior will save the image to the cwd with whatever name its temp file has, right?

I can test and merge later, currently on windows.

**Comment by Bekaboo** [comment]
It just fills the cwd as a preset default response. User can edit the path to their likings.

**Comment by benlubas** [comment]
Oh I see. You can give a relative path and it'll be relative to the current working directory in the current implementation.

I do think I like having the path prefilled better though, it's a little more clear that way.

**Comment by Bekaboo** [comment]
> You can give a relative path and it'll be relative to the current working directory in the current implementation.

@benlubas Done

**Comment by benlubas** [comment]
@Bekaboo, sorry, I meant that's how it works currently, before this PR.

I like your original solution. This PR currently seems to behave the same way as before (the default string appears to be empty). Prefilling the path to cwd is a good way to remind the user of the cwd, while still letting them use a relative file path if then want. `/home/benlubas/path/to/cwd/../image.png` will work just fine with the original solution.

It also lets you just hit enter to save the file with whatever filename it had before, which is convenient.

So could you just revert [`c207cb1`](https://github.com/benlubas/image-save.nvim/pull/1/commits/c207cb129aa462f13de64015bd115b9ae16f394c)

**Comment by Bekaboo** [comment]
@benlubas OK, done.

**Comment by benlubas** [comment]
thanks!

**Pull request merged**
